#orange:                    #useful if you use a namespace for the robot
    # Publish joint states
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

orange_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - pan
      - tilt
    gains:
      pan: { p: 12000, i: 50, d: 0.0, i_clamp: 10000 }
      tilt: { p: 30000, i: 100, d: 0.02, i_clamp: 10000 }

    constraints:
        goal_time: 2.0

    state_publish_rate: 25
