#orange:                    #useful if you use a namespace for the robot
    # Publish joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    panda_arm_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - pan
            - tilt

        gains:
            pan: { p: 5, d: 1, i: 0.0 }
            tilt: { p: 5, d: 1, i: 0.0 }

        constraints:
            goal_time: 2.0

        state_publish_rate: 25
