joint1_controller:
    controller:
        package: dynamixel_workbench_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder # joint1
    joint_speed: 0.1
    motor:
        id: 1
        init: 2048 # initial position
        min: 100 # 320 minimum limit of the joint
        max: 4005 #3823  maximum limit of the joint


joint2_controller:
    controller:
        package: dynamixel_workbench_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: elbow # joint2
    joint_speed: 0.1
    motor:
        id: 2
        init: 2048
        min: 100 # 957
        max: 4005 # 3106
