orange_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pan
    - tilt
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      pan: {trajectory: 0.1, goal: 0.1}
      tilt: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

/gazebo_ros_control:
  pid_gains:
    pan:
      p: 100.0
      i: 1.0
      d: 0.1
    tilt:
      p: 100.0
      i: 1.0
      d: 0.1
